/**
 * @a2ui-bridge/react-shadcn - Default ShadCN theme
 * MIT License - Copyright (c) 2025 Southleft
 *
 * Uses explicit Tailwind colors for reliable rendering without CSS variables.
 * All colors support both light and dark mode via dark: prefix.
 */

import type { Theme } from '@a2ui-bridge/core';

/**
 * Default ShadCN-style theme using Tailwind CSS classes.
 */
export const defaultTheme: Theme = {
  components: {
    AudioPlayer: {},
    Badge: {
      'inline-flex': true,
      'items-center': true,
      'rounded-full': true,
      'border': true,
      'border-zinc-200': true,
      'dark:border-zinc-700': true,
      'bg-zinc-100': true,
      'dark:bg-zinc-800': true,
      'px-2.5': true,
      'py-0.5': true,
      'text-xs': true,
      'font-semibold': true,
      'text-zinc-700': true,
      'dark:text-zinc-300': true,
      'transition-colors': true,
    },
    Button: {
      'inline-flex': true,
      'items-center': true,
      'justify-center': true,
      'whitespace-nowrap': true,
      'rounded-md': true,
      'text-sm': true,
      'font-medium': true,
      'transition-colors': true,
      'focus-visible:outline-none': true,
      'focus-visible:ring-2': true,
      'focus-visible:ring-zinc-400': true,
      'focus-visible:ring-offset-2': true,
      'disabled:pointer-events-none': true,
      'disabled:opacity-50': true,
      'bg-zinc-900': true,
      'dark:bg-zinc-100': true,
      'text-white': true,
      'dark:text-zinc-900': true,
      'hover:bg-zinc-800': true,
      'dark:hover:bg-zinc-200': true,
      'h-10': true,
      'px-4': true,
      'py-2': true,
    },
    Card: {
      'rounded-lg': true,
      'border': true,
      'border-zinc-200': true,
      'dark:border-zinc-700': true,
      'bg-white': true,
      'dark:bg-zinc-900': true,
      'text-zinc-900': true,
      'dark:text-zinc-100': true,
      'shadow-sm': true,
      'p-6': true,
    },
    Column: {
      'flex': true,
      'flex-col': true,
      'gap-3': true,
    },
    CheckBox: {
      container: {
        'flex': true,
        'items-center': true,
        'space-x-2': true,
      },
      element: {
        'peer': true,
        'h-4': true,
        'w-4': true,
        'shrink-0': true,
        'rounded-sm': true,
        'border': true,
        'border-zinc-300': true,
        'dark:border-zinc-600': true,
        'focus-visible:outline-none': true,
        'focus-visible:ring-2': true,
        'focus-visible:ring-zinc-400': true,
        'focus-visible:ring-offset-2': true,
        'disabled:cursor-not-allowed': true,
        'disabled:opacity-50': true,
      },
      label: {
        'text-sm': true,
        'font-medium': true,
        'text-zinc-700': true,
        'dark:text-zinc-300': true,
        'leading-none': true,
        'peer-disabled:cursor-not-allowed': true,
        'peer-disabled:opacity-70': true,
      },
    },
    DateTimeInput: {
      container: {
        'grid': true,
        'w-full': true,
        'gap-1.5': true,
      },
      element: {
        'flex': true,
        'h-10': true,
        'w-full': true,
        'rounded-md': true,
        'border': true,
        'border-zinc-200': true,
        'dark:border-zinc-700': true,
        'bg-white': true,
        'dark:bg-zinc-900': true,
        'px-3': true,
        'py-2': true,
        'text-sm': true,
        'text-zinc-900': true,
        'dark:text-zinc-100': true,
        'focus-visible:outline-none': true,
        'focus-visible:ring-2': true,
        'focus-visible:ring-zinc-400': true,
        'focus-visible:ring-offset-2': true,
        'disabled:cursor-not-allowed': true,
        'disabled:opacity-50': true,
      },
      label: {
        'text-sm': true,
        'font-medium': true,
        'text-zinc-700': true,
        'dark:text-zinc-300': true,
        'leading-none': true,
      },
    },
    Divider: {
      'shrink-0': true,
      'bg-zinc-200': true,
      'dark:bg-zinc-700': true,
      'h-[1px]': true,
      'w-full': true,
      'my-4': true,
    },
    Grid: {
      'grid': true,
      'gap-4': true,
    },
    Image: {
      all: {},
      icon: {
        'w-6': true,
        'h-6': true,
      },
      avatar: {
        'w-10': true,
        'h-10': true,
        'rounded-full': true,
      },
      smallFeature: {
        'w-full': true,
        'max-w-xs': true,
        'rounded-md': true,
      },
      mediumFeature: {
        'w-full': true,
        'max-w-md': true,
        'rounded-md': true,
      },
      largeFeature: {
        'w-full': true,
        'max-w-lg': true,
        'rounded-md': true,
      },
      header: {
        'w-full': true,
        'rounded-t-lg': true,
      },
    },
    Icon: {
      'w-5': true,
      'h-5': true,
      'text-zinc-600': true,
      'dark:text-zinc-400': true,
    },
    List: {
      'flex': true,
      'flex-col': true,
      'gap-2': true,
    },
    Modal: {
      backdrop: {
        'fixed': true,
        'inset-0': true,
        'z-50': true,
        'bg-black/80': true,
      },
      element: {
        'fixed': true,
        'left-[50%]': true,
        'top-[50%]': true,
        'z-50': true,
        'grid': true,
        'w-full': true,
        'max-w-lg': true,
        'translate-x-[-50%]': true,
        'translate-y-[-50%]': true,
        'gap-4': true,
        'border': true,
        'border-zinc-200': true,
        'dark:border-zinc-700': true,
        'bg-white': true,
        'dark:bg-zinc-900': true,
        'p-6': true,
        'shadow-lg': true,
        'sm:rounded-lg': true,
      },
    },
    MultipleChoice: {
      container: {
        'grid': true,
        'w-full': true,
        'gap-1.5': true,
      },
      element: {
        'flex': true,
        'h-10': true,
        'w-full': true,
        'rounded-md': true,
        'border': true,
        'border-zinc-200': true,
        'dark:border-zinc-700': true,
        'bg-white': true,
        'dark:bg-zinc-900': true,
        'px-3': true,
        'py-2': true,
        'text-sm': true,
        'text-zinc-900': true,
        'dark:text-zinc-100': true,
        'focus-visible:outline-none': true,
        'focus-visible:ring-2': true,
        'focus-visible:ring-zinc-400': true,
        'focus-visible:ring-offset-2': true,
        'disabled:cursor-not-allowed': true,
        'disabled:opacity-50': true,
      },
      label: {
        'text-sm': true,
        'font-medium': true,
        'text-zinc-700': true,
        'dark:text-zinc-300': true,
        'leading-none': true,
      },
    },
    Row: {
      'flex': true,
      'flex-row': true,
      'gap-3': true,
      'items-center': true,
    },
    Select: {},
    Slider: {
      container: {
        'grid': true,
        'w-full': true,
        'gap-1.5': true,
      },
      element: {
        'w-full': true,
        'h-2': true,
        'bg-zinc-200': true,
        'dark:bg-zinc-700': true,
        'rounded-lg': true,
        'appearance-none': true,
        'cursor-pointer': true,
      },
      label: {
        'text-sm': true,
        'text-zinc-500': true,
        'dark:text-zinc-400': true,
      },
    },
    Tabs: {
      container: {
        'w-full': true,
      },
      element: {
        'mt-2': true,
      },
      controls: {
        all: {
          'inline-flex': true,
          'h-10': true,
          'items-center': true,
          'justify-center': true,
          'rounded-md': true,
          'bg-zinc-100': true,
          'dark:bg-zinc-800': true,
          'p-1': true,
          'text-zinc-500': true,
          'dark:text-zinc-400': true,
        },
        selected: {
          'bg-white': true,
          'dark:bg-zinc-900': true,
          'text-zinc-900': true,
          'dark:text-zinc-100': true,
          'shadow-sm': true,
        },
      },
    },
    Text: {
      all: {
        'text-zinc-700': true,
        'dark:text-zinc-300': true,
      },
      h1: {
        'scroll-m-20': true,
        'text-4xl': true,
        'font-extrabold': true,
        'tracking-tight': true,
        'text-zinc-900': true,
        'dark:text-zinc-50': true,
        'lg:text-5xl': true,
      },
      h2: {
        'scroll-m-20': true,
        'border-b': true,
        'border-zinc-200': true,
        'dark:border-zinc-700': true,
        'pb-2': true,
        'text-3xl': true,
        'font-semibold': true,
        'tracking-tight': true,
        'text-zinc-900': true,
        'dark:text-zinc-50': true,
        'first:mt-0': true,
      },
      h3: {
        'scroll-m-20': true,
        'text-2xl': true,
        'font-semibold': true,
        'tracking-tight': true,
        'text-zinc-800': true,
        'dark:text-zinc-100': true,
      },
      h4: {
        'scroll-m-20': true,
        'text-xl': true,
        'font-semibold': true,
        'tracking-tight': true,
        'text-zinc-800': true,
        'dark:text-zinc-100': true,
      },
      h5: {
        'scroll-m-20': true,
        'text-lg': true,
        'font-semibold': true,
        'tracking-tight': true,
        'text-zinc-700': true,
        'dark:text-zinc-200': true,
      },
      caption: {
        'text-sm': true,
        'text-zinc-500': true,
        'dark:text-zinc-400': true,
      },
      body: {
        'leading-7': true,
        'text-zinc-700': true,
        'dark:text-zinc-300': true,
      },
    },
    TextField: {
      container: {
        'grid': true,
        'w-full': true,
        'gap-1.5': true,
      },
      element: {
        'flex': true,
        'h-10': true,
        'w-full': true,
        'rounded-md': true,
        'border': true,
        'border-zinc-200': true,
        'dark:border-zinc-700': true,
        'bg-white': true,
        'dark:bg-zinc-900': true,
        'px-3': true,
        'py-2': true,
        'text-sm': true,
        'text-zinc-900': true,
        'dark:text-zinc-100': true,
        'file:border-0': true,
        'file:bg-transparent': true,
        'file:text-sm': true,
        'file:font-medium': true,
        'placeholder:text-zinc-400': true,
        'dark:placeholder:text-zinc-500': true,
        'focus-visible:outline-none': true,
        'focus-visible:ring-2': true,
        'focus-visible:ring-zinc-400': true,
        'focus-visible:ring-offset-2': true,
        'disabled:cursor-not-allowed': true,
        'disabled:opacity-50': true,
      },
      label: {
        'text-sm': true,
        'font-medium': true,
        'text-zinc-700': true,
        'dark:text-zinc-300': true,
        'leading-none': true,
        'peer-disabled:cursor-not-allowed': true,
        'peer-disabled:opacity-70': true,
      },
    },
    Video: {},
  },
  elements: {
    a: {},
    audio: {},
    body: {},
    button: {},
    h1: {},
    h2: {},
    h3: {},
    h4: {},
    h5: {},
    iframe: {},
    input: {},
    p: {},
    pre: {},
    textarea: {},
    video: {},
  },
  markdown: {
    p: ['leading-7', 'text-zinc-700', 'dark:text-zinc-300'],
    h1: ['scroll-m-20', 'text-4xl', 'font-extrabold', 'tracking-tight', 'text-zinc-900', 'dark:text-zinc-50'],
    h2: ['scroll-m-20', 'text-3xl', 'font-semibold', 'tracking-tight', 'text-zinc-900', 'dark:text-zinc-50'],
    h3: ['scroll-m-20', 'text-2xl', 'font-semibold', 'tracking-tight', 'text-zinc-800', 'dark:text-zinc-100'],
    h4: ['scroll-m-20', 'text-xl', 'font-semibold', 'tracking-tight', 'text-zinc-800', 'dark:text-zinc-100'],
    h5: ['scroll-m-20', 'text-lg', 'font-semibold', 'tracking-tight', 'text-zinc-700', 'dark:text-zinc-200'],
    ul: ['my-6', 'ml-6', 'list-disc', 'text-zinc-700', 'dark:text-zinc-300'],
    ol: ['my-6', 'ml-6', 'list-decimal', 'text-zinc-700', 'dark:text-zinc-300'],
    li: ['mt-2'],
    a: ['font-medium', 'text-blue-600', 'dark:text-blue-400', 'underline', 'underline-offset-4'],
    strong: ['font-semibold', 'text-zinc-900', 'dark:text-zinc-100'],
    em: ['italic'],
  },
};
